config/routes.rb
Rails.application.routes.draw do
  
  
  root 'public#index'
  get 'show/:permalink', :to => 'public#show', :as => "public_show"
  get 'admin_users/index'
  get 'admin_users/new'
  get 'admin_users/edit'
  get 'admin_users/delete'


  root 'demo#index' #no need to write demo/index only demo will do fine
  get 'demo/index' #have to write full and proper demo/index

  get 'demo/hello'
  get 'demo/other'

  get 'admin', :to => 'access#menu'
  get 'access/menu' #index
  get 'access/login' #new
  post 'access/attempt_login' # create POST
  get 'access/logout' #destroy
  
  
  # get 'admin_users/index'
  # get 'admin_users/new'
  # get 'admin_users/edit'
  # get 'admin_users/delete'

  resources :admin_users, :except => [:show] do
    member do
      get :delete
    end
  end


  # get ':controller(/:action(/:page))' 
  #this is a default routes run for anything  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html



#these are match routes 
  # get 'sections/index'
  # get 'sections/show'
  # get 'sections/new'
  # get 'sections/delete'
  # get 'sections/edit'
#these are resource routes 
  resources :sections do
    member do
      get :delete
    end 
  end 
  # get 'pages/index'
  # get 'pages/show'
  # get 'pages/new'
  # get 'pages/edit'
  # get 'pages/delete'
  resources :pages do
    member do
      get :delete
    end 
  end 
  
  


  
  # get 'subjects/index'
  # get 'subjects/show'
  # get 'subjects/new'
  # get 'subjects/edit'
  # get 'subjects/delete' # automatically generated no need instead we use 
  resources :subjects do #by defualt delete is not included in it so thats why we include it explicity 
    member do
      get :delete 
      #delete_subject GET    /subjects/:id/delete(.:format)       subjects#delete
    end
  end

  namespace 'api' do
    namespace 'v1' do
      resources :subjects,:pages,:sections
    end
  end

end

app/models/section.rb
class Section < ApplicationRecord
    #acts_as_list :scope => :subject
    
    belongs_to :page
    has_many :section_edits
    has_many :admin_users, :through => :section_edits

    scope :visible , lambda {where(:visible => true) }
    scope :invisible , lambda { where(:visible => false) }
    scope :sorted , lambda { order("position ASC") }
    scope :newest_first , lambda { order(:created_at => :desc ) }
    scope :search , lambda { |query| where(["name LIKE ?", "%#{query}%"] ) }

    CONTENT_TYPES = ['Text','HTML'] #constant

    validates_presence_of :name 
    validates_length_of :name, :maximum => 255
    validates_inclusion_of :content_type, :in => CONTENT_TYPES,
     :message => "must be one of: #{CONTENT_TYPES.join(', ')}"
     validates_presence_of :content
end

app/controllers/api/v1/sections_controller.rb
module Api
    module V1
        class SectionsController < ApplicationController
  # skip_before_filter :verify_authenticity_token, if: :json_request? #For some reason I'm getting an InvalidAuthenticityToken when making post requests to my application when using json
   skip_before_action :verify_authenticity_token########  WARNING is this secure??

  # Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
#gem 'jbuilder', '~> 2.5'

            def index
                sections = Section.order('created_at DESC')
                render json: {status: 'SUCCESS', message: 'Loaded Sections', data:sections},status: :ok
            end

            def show
                section = Section.find(params[:id])
                render json: {status: 'SUCCESS', message: 'Loaded Section', data:section},status: :ok
            end
            def create
                section = Section.new(section_params)
                if section.save
                    render json: {status: 'SUCCESS', message: 'Saved Section', data:section},status: :ok
                else
                    render json: {status: 'ERROR', message: 'Section not saved', data:section.errors},status: :unprocessable_entity
                end
            end
            def destroy
                section = Section.find(params[:id])
                section.destroy
                render json: {status: 'SUCCESS', message: 'Deleted Section', data:section},status: :ok
            end
            def update
                section = Section.find(params[:id])
                if section.update_attributes(section_params)
                    render json: {status: 'SUCCESS', message: 'Update Section', data:section},status: :ok
                else
                    render json: {status: 'ERROR', message: 'Section not update', data:section.errors},status: :unprocessable_entity
                end
            end

            private

            def section_params
                params.require(:section).permit(:page_id, :name, :position, :visible, :content_type, :content)
            end
        end
    end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  layout 'admin'

  before_action :confirm_logged_in #see the applicationController 

  before_action :find_page
  def index
    @sections = @page.sections.all
  end

  def show
    @section = @page.sections.find(params[:id])
  end

  def new
    @section = Section.new(:page_id => @page.id)
    @section_count = @page.sections.count + 1
    @pages =  Page.sorted
  end

  def create
    section = Section.new(section_params)

    if section.save
      flash[:notice] = "Section Created Successfully"
      redirect_to(sections_path(:page_id => @page.id))
    else
      section_count = @page.sections.count + 1
      @pages =  Page.sorted
      render "new"
    end
  end

  def delete
    @section = Section.find(params[:id])
  end

  def destroy
    @section = Section.find(params[:id])
    @section.destroy
    flash[:notice] = "Section Deleted Successfully"
    redirect_to(pages_path(:page_id => @page.id))
    
  end

  def edit
    @section = Section.find(params[:id])
    @section_count = @page.sections.count
    @pages =  Page.sorted
  end
  def update
    @section = Section.find(params[:id])
    
    if @section.update_attributes(section_params)
      flash[:notice] = "Section Updated Successfully"
      redirect_to(section_path(@section , :page_id => @page.id))
    else
      @section_count = @page.sections.count
      @pages =  Page.sorted
      render 'edit'
    end
  end

private 

  def section_params
    params.require(:section).permit(:page_id, :name, :position, :visible, :content_type, :content)
  end
  # find page count  implement in page controller and a one trick is there
  #i am creating a new section and it gives me a position for select out of 7 
  # but on that page i have only two how to tackle this 

  def find_page
    @page = Page.find(params[:page_id])
  end
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/sections/_form.html.erb
    <%= error_messages_for(f.object) %>
    <%# this function is in our helper don't need to write it over and over for others page and sections%>
  <table summary="Section form fields">
      <tr>
        <th>Name</th>
        <td><%= f.text_field(:name) %></td>
      </tr>
      <tr>
        <th>Page</th> 
        <td><%= f.select(:page_id, @pages.map {|s| [s.name, s.id]}) %></td>
        <!-- 
          we have three options here in edit or new 
          user can choose the page and jump around 
          we can disable this options 
          we can remove and show a page name only because user go to that specific subject and then specific page and then can create the section 
          so i think it is good option for remove it at all and replace select tag with this one below but personally i dont want to :) badmashi
          
          
          -->
        <!-- f.object.page.name 
            and this is not just it we no have to remove this by params list because it is not going from form any more page or subject 
            so we have to mention in give subject id or page id at creataion of new page or section in controller 
            like @page.subject_id = @subject.id     or in short form 
            @page.subject = subject     do the work for us       and can remove a before action :find_subjects  that is there for select option 
            
            now i am changing my mind because we have to hit data base just for this or i have a new approach why not i do pass the subjects parameters 
            but i think then i have to maintain the status of it 
        
        -->
      </tr>
      <tr>
        <th>Position</th>
        <td><%= f.select(:position, 1..@section_count) %></td>
      </tr>
      <tr>
        <th>Visible</th>
        <td><%= f.check_box(:visible) %></td>
      </tr>
      <tr>
        <th>Content Type</th>
        <td>
            <%= f.radio_button(:content_type, "Text") %> Text 
            <%= f.radio_button(:content_type, "HTML") %> HTML
        </td>
      </tr>
      <tr>
        <th>Content</th>
        <td><%= f.text_area(:content, :size => "40x10") %></td>
      </tr>
    </table>

app/views/sections/delete.html.erb
<%= link_to("<< Back to List", sections_path(:page_id => @page.id), :class => 'back-link') %>

<div class="sections delete">
  <h2>Delete Sections</h2>
  
  <%= form_for(@section, :url => section_path(@section, :page_id => @page.id), :method => 'delete') do |f| %> 
<%# you can ommit the url part but not :method => delete you have to specify this  %>
    <p>Are you sure you want to permanently delete this section?</p>

    <p class="reference-name"><%= f.object.name %></p>
    <%# notice f.object.name however sebject.name is totally workout for us fine %>

    <div class="form-buttons">
      <%= f.submit("Delete Section") %>
    </div>

  <% end %>
</div>

app/views/sections/edit.html.erb
<%= link_to("<< Back to List", sections_path(:page_id => @page.id), :class => 'back-link') %>

<div class="section edit">
  <h2>Update section</h2>

  <%= form_for(@section, :url => section_path(@section, :page_id => @page), :method => 'patch') do |f| %>
  <%# form_for(@section) do |f|  #we dont have to specify them becuase you are post something and see rails route %>    

    <%= render(:partial => "form" , :locals => {:f => f}) %>


    <div class="form-buttons">
      <%= f.submit("Update Section") %>
    </div>

  <% end %>
</div>

app/views/sections/index.html.erb
<div class="sections index">

<%= link_to("<< Back to Pages", pages_path(:subject_id => @page.subject_id), :class => 'back-link') %>

  <h2>sections</h2>

  <%# link_to("Add New Subject", 'subjects/new', :class => 'action new') %>
  <%= link_to("Add New Section", new_section_path(:page_id => @page.id) , :class => 'action new') %>

  <table class="listing" summary="section list">
    <tr class="header">
      <th>Position</th>
      <th>Page ID</th>
      <th>Section</th>
      <th>Visible</th>
      <th>Content Type</th>
      <th>Content</th>
      <th>Acitons</th>
    </tr>
    <% @sections.each do |section| %>
    <tr>
      <td><%= section.position %></td>
      <td><%= section.page_id %></td>
      <td><%= section.name %></td>
      <td class="center"><%= section.visible ? 'Yes' : 'No' %></td>
      <td class="center"><%= section.content_type %></td>
      <td class="center"><%= strip_tags(section.content) %></td>
      <td class="actions">
        <%# link_to("Show", 'subjects#{subject.id}', :class => 'action show') %>
        <%# link_to("Show", {:controller => 'subjects' , :action => 'show', :id => subject.id }, :class => 'action show') %>
        <%= link_to("Show", section_path(section, :page_id => @page.id), :class => 'action show') %>
        <%= link_to("Edit", edit_section_path(section, :page_id => @page.id), :class => 'action edit') %>
        <%= link_to("Delete", delete_section_path(section, :page_id => @page.id), :class => 'action delete') %>
      </td>
    </tr>
    <% end %>
  </table>
</div>

app/views/sections/new.html.erb
<%= link_to("<< Back to List", sections_path(:page_id => @page.id), :class => 'back-link') %>

<div class="section new">
  <h2>Create Section</h2>

  <%= form_for(@section, :url => sections_path(:page_id => @page.id), :method => 'post') do |f| %>
  <%# form_for(@subject) do |f|     we dont have to specify them becuase you are post something and see rails route %> 

    <%= render(:partial => "form" , :locals => {:f => f }) %>

    <div class="form-buttons">
      <%= f.submit("Create section") %>
    </div>

  <% end %>
</div>

app/views/sections/show.html.erb
<%= link_to("<< Back to Page", sections_path(:page_id => @page.id), :class => 'back-link') %>

<div class="section show">
  <h2>Show Section</h2>

  <table summary="Section detail view">
  <tr>
      <th>Page ID</th>
      <td><%= @section.page_id %></td>
    </tr>
    <tr>
      <th>Name</th>
      <td><%= @section.name %></td>
    </tr>
    <tr>
      <th>Position</th>
      <td><%= @section.position %></td>
    </tr>
    <tr>
      <th>Visible</th>
      <td><%= @section.visible ? 'true' : 'false' %></td>
    </tr>
    <tr>
      <th>Content Type</th>
      <td><%= @section.content_type %></td>
    </tr>
    <tr>
      <th>Content</th>
      <td><%= sanitize(@section.content,tags: ['p','br','strong','em','h6','h5','h4','h3','h2','em','hr','b','u' ]) %></td>
    </tr>
    <tr>
      <th>Created</th>
      <td><%= @section.created_at.strftime("%d/%m/%Y at %I:%M%p") %></td>
    </tr>
    <tr>
      <th>Updated</th>
      <td><%= @section.updated_at.strftime("%d/%m/%Y at %I:%M%p") %></td>
    </tr>
  </table>

</div>