config/routes.rb
Rails.application.routes.draw do
  
  
  root 'public#index'
  get 'show/:permalink', :to => 'public#show', :as => "public_show"
  get 'admin_users/index'
  get 'admin_users/new'
  get 'admin_users/edit'
  get 'admin_users/delete'


  root 'demo#index' #no need to write demo/index only demo will do fine
  get 'demo/index' #have to write full and proper demo/index

  get 'demo/hello'
  get 'demo/other'

  get 'admin', :to => 'access#menu'
  get 'access/menu' #index
  get 'access/login' #new
  post 'access/attempt_login' # create POST
  get 'access/logout' #destroy
  
  
  # get 'admin_users/index'
  # get 'admin_users/new'
  # get 'admin_users/edit'
  # get 'admin_users/delete'

  resources :admin_users, :except => [:show] do
    member do
      get :delete
    end
  end


  # get ':controller(/:action(/:page))' 
  #this is a default routes run for anything  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html



#these are match routes 
  # get 'sections/index'
  # get 'sections/show'
  # get 'sections/new'
  # get 'sections/delete'
  # get 'sections/edit'
#these are resource routes 
  resources :sections do
    member do
      get :delete
    end 
  end 
  # get 'pages/index'
  # get 'pages/show'
  # get 'pages/new'
  # get 'pages/edit'
  # get 'pages/delete'
  resources :pages do
    member do
      get :delete
    end 
  end 
  
  


  
  # get 'subjects/index'
  # get 'subjects/show'
  # get 'subjects/new'
  # get 'subjects/edit'
  # get 'subjects/delete' # automatically generated no need instead we use 
  resources :subjects do #by defualt delete is not included in it so thats why we include it explicity 
    member do
      get :delete 
      #delete_subject GET    /subjects/:id/delete(.:format)       subjects#delete
    end
  end

  namespace 'api' do
    namespace 'v1' do
      resources :subjects,:pages,:sections
    end
  end

end

app/views/pages/_form.html.erb
<%= error_messages_for(f.object) %>
    <%# this function is in our helper don't need to write it over and over for others page and sections %>

<table summary="Page form fields">
      <tr>
        <th>Name</th>
        <td><%= f.text_field(:name) %></td>
      </tr>
      <tr>
        <th>Subject</th>
        <td><%= f.select(:subject_id, @subjects.map {|s| [s.name, s.id]}) %></td>
      </tr>
      <tr>
        <th>Permalink</th>
        <td><%= f.text_field(:permalink) %></td>
      </tr>
      <tr>
        <th>Position</th>
        <td><%= f.select(:position, 1..@page_count) %></td>
      </tr>
      <tr>
        <th>Visible</th>
        <td><%= f.check_box(:visible) %></td>
      </tr>
    </table>

app/views/pages/delete.html.erb
<%= link_to("<< Back to List", pages_path(:subject_id => @subject.id), :class => 'back-link') %>

<div class="Pages delete">
  <h2>Delete Page</h2>
  
  <%= form_for(@page, :url => subject_path(@page), :method => 'delete') do |f| %> 
<%# you can ommit the url part but not :method => delete you have to specify this  %>
    <p>Are you sure you want to permanently delete this Page?</p>

    <p class="reference-name"><%= f.object.name %></p>
    <%# notice f.object.name however sebject.name is totally workout for us fine %>

    <div class="form-buttons">
      <%= f.submit("Delete Page") %>
    </div>

  <% end %>
</div>

app/views/pages/edit.html.erb
<%= link_to("<< Back to List", pages_path(:subject_id => @subject.id), :class => 'back-link') %>

<div class="subjects edit">
  <h2>Update Page</h2>

  <%= form_for(@page, :url => page_path(@page, :subject_id => @subject.id), :method => 'patch') do |f| %>
  <%# form_for(@subject) do |f| %>    <%#we dont have to specify them becuase you are post something and see rails route %>

    <%= render(:partial => "form" , :locals => {:f => f}) %>

    <div class="form-buttons">
      <%= f.submit("Update Page") %>
    </div>

  <% end %>
</div>

app/views/pages/index.html.erb
<% @page_title = "All Pages" %>

<%= link_to("<< Back to Subjects", subjects_path, :class => 'back-link') %>
<div class="pages index">
  <h2>Pages</h2>

  <%# link_to("Add New Subject", 'subjects/new', :class => 'action new') %>
  <%= link_to("Add New Page", new_page_path(:subject_id => @subject.id) , :class => 'action new') %>

  <table class="listing" summary="page list">
    <tr class="header">
      <th>Position</th>
      <th>Subject ID</th>
      <th>Page</th>
      <th>Permalinks</th>
      <th>Visible</th>
      <th>Sections</th>
      <th>Actions</th>
    </tr>
    <% @pages.each do |page| %>
    <tr>
      <td><%= page.position %></td>
      <td><%= page.subject_id %></td>
      <td><%= page.name %></td>
      <td><%= page.permalink %></td>
      <td class="center"><%= status_tag(page.visible) %></td>
      <td class="center"><%= page.sections.size %></td>
      <td class="actions">
        <%# link_to("Show", 'subjects#{subject.id}', :class => 'action show') %>
        <%# link_to("Show", {:controller => 'subjects' , :action => 'show', :id => subject.id }, :class => 'action show') %>
        <%# link_to("View Sections", sections_path(:subject_id => @subject.id , :page_id => page.id), :class => 'action show') %>
        <!-- above here  that is my approach but we get the subject by the page because page has also a subject id --->
        <%= link_to("View Sections", sections_path(:page_id => page.id), :class => 'action show') %>
        <%= link_to("Show", page_path(page, :subject_id => @subject.id), :class => 'action show') %>
        <%= link_to("Edit", edit_page_path(page, :subject_id => @subject.id), :class => 'action edit') %>
        <%= link_to("Delete", delete_page_path(page, :subject_id => @subject.id), :class => 'action delete') %>
      </td>
    </tr>
    <% end %>
  </table>
</div>

app/views/pages/new.html.erb
<%= link_to("<< Back to List", pages_path(:subject_id => @subject.id), :class => 'back-link') %>

<div class="subjects new">
  <h2>Create Page</h2>

  <%= form_for(@page, :url => pages_path(:subject_id => @subject.id), :method => 'post') do |f| %>
  <%# form_for(@subject) do |f|     we dont have to specify them becuase you are post something and see rails route %> 
  <%# but now after in end we want to track of subject id so this is must now %>
    <%= render(:partial =>"form", :locals => {:f => f}) %>
    <%# partial reusable eletment notice in our form we use 'f' 
    its not gonna available their we have to send it %>

    <div class="form-buttons">
      <%= f.submit("Create Page") %>
    </div>

  <% end %>
</div>

app/views/pages/show.html.erb
<%= link_to("<< Back to List", pages_path(:subject_id => @subject.id), :class => 'back-link') %>

<div class="pages">
  <h2>Show Pages</h2>

  <table summary="Page detail view">
  <tr>
      <th>Subject ID</th>
      <td><%= @page.subject_id %></td>
    </tr>
    <tr>
      <th>Name</th>
      <td><%= @page.name %></td>
    </tr>
    <tr>
      <th>Permalink</th>
      <td><%= @page.permalink %></td>
    </tr>
    <tr>
      <th>Position</th>
      <td><%= @page.position %></td>
    </tr>
    <tr>
      <th>Visible</th>
      <td><%= @page.visible ? 'true' : 'false' %></td>
    </tr>
    <tr>
      <th>Created</th>
      <td><%= @page.created_at.strftime("%d/%m/%Y at %I:%M%p") %></td>
    </tr>
    <tr>
      <th>Updated</th>
      <td><%= @page.updated_at.strftime("%d/%m/%Y at %I:%M%p") %></td>
    </tr>
  </table>

</div>