config/routes.rb
Rails.application.routes.draw do
  
  
  root 'public#index'
  get 'show/:permalink', :to => 'public#show', :as => "public_show"
  get 'admin_users/index'
  get 'admin_users/new'
  get 'admin_users/edit'
  get 'admin_users/delete'


  root 'demo#index' #no need to write demo/index only demo will do fine
  get 'demo/index' #have to write full and proper demo/index

  get 'demo/hello'
  get 'demo/other'

  get 'admin', :to => 'access#menu'
  get 'access/menu' #index
  get 'access/login' #new
  post 'access/attempt_login' # create POST
  get 'access/logout' #destroy
  
  
  # get 'admin_users/index'
  # get 'admin_users/new'
  # get 'admin_users/edit'
  # get 'admin_users/delete'

  resources :admin_users, :except => [:show] do
    member do
      get :delete
    end
  end


  # get ':controller(/:action(/:page))' 
  #this is a default routes run for anything  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html



#these are match routes 
  # get 'sections/index'
  # get 'sections/show'
  # get 'sections/new'
  # get 'sections/delete'
  # get 'sections/edit'
#these are resource routes 
  resources :sections do
    member do
      get :delete
    end 
  end 
  # get 'pages/index'
  # get 'pages/show'
  # get 'pages/new'
  # get 'pages/edit'
  # get 'pages/delete'
  resources :pages do
    member do
      get :delete
    end 
  end 
  
  


  
  # get 'subjects/index'
  # get 'subjects/show'
  # get 'subjects/new'
  # get 'subjects/edit'
  # get 'subjects/delete' # automatically generated no need instead we use 
  resources :subjects do #by defualt delete is not included in it so thats why we include it explicity 
    member do
      get :delete 
      #delete_subject GET    /subjects/:id/delete(.:format)       subjects#delete
    end
  end

  namespace 'api' do
    namespace 'v1' do
      resources :subjects,:pages,:sections
    end
  end

end

app/models/subject.rb
class Subject < ApplicationRecord

    acts_as_list #gem 

    has_many :pages
    #Subject -> Page -> Section
    #Cyberpunk -> Security -> Honey Pot

    #scope lambda syntax

    scope :visible , lambda {where(:visible => true) }
    scope :invisible , lambda { where(:visible => false) }
    scope :sorted , lambda { order("position ASC") }
    scope :newest_first , lambda { order(:created_at => :desc ) }
    scope :search , lambda { |query| where(["name LIKE ?", "%#{query}%"] ) }

    validates_presence_of :name #space also consider blank 
    validates_length_of :name, :maximum => 255

end

app/controllers/api/v1/subjects_controller.rb
module Api
    module V1
        class SubjectsController < ApplicationController
  # skip_before_filter :verify_authenticity_token, if: :json_request? #For some reason I'm getting an InvalidAuthenticityToken when making post requests to my application when using json
   skip_before_action :verify_authenticity_token########  WARNING is this secure??

  # Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
#gem 'jbuilder', '~> 2.5'

            def index
                subjects = Subject.order('created_at DESC')
                render json: {status: 'SUCCESS', message: 'Loaded Subjects', data:subjects},status: :ok
            end

            def show
                subject = Subject.find(params[:id])
                render json: {status: 'SUCCESS', message: 'Loaded Subject', data:subject},status: :ok
            end
            def create
                subject = Subject.new(subject_params)
                if subject.save
                    render json: {status: 'SUCCESS', message: 'Saved Subject', data:subject},status: :ok
                else
                    render json: {status: 'ERROR', message: 'Subject not saved', data:subject.errors},status: :unprocessable_entity
                end
            end
            def destroy
                subject = Subject.find(params[:id])
                subject.destroy
                render json: {status: 'SUCCESS', message: 'Deleted Subject', data:subject},status: :ok
            end
            def update
                subject = Subject.find(params[:id])
                if subject.update_attributes(subject_params)
                    render json: {status: 'SUCCESS', message: 'Update Subject', data:subject},status: :ok
                else
                    render json: {status: 'ERROR', message: 'Subject not update', data:subject.errors},status: :unprocessable_entity
                end
            end

            private

            def subject_params
                params.require(:subject).permit(:name, :position, :visible)
            end
# PATCH/PUT /posts/1
# PATCH/PUT /posts/1.json
#   def update
#     respond_to do |format|
#       if @post.update(post_params)
#         format.html { redirect_to @post, success: 'Post was successfully updated.' }
#         format.json { render :show, status: :ok, location: @post }
#       else
#         format.html { render :edit }
#         format.json { render json: @post.errors, status: :unprocessable_entity }
#       end
#     end
#   end

        end
    end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  layout 'admin'
  
  before_action :confirm_logged_in #see the applicationController 
  # GET /subjects
  # GET /subjects.json
  def index ################################################################
    @subjects = Subject.sorted  #used lambda scope subject model instead of Subject.all return randomly we want to return in sorted order
    @page_title = "All Subject"
    #render('index') rails is smart no need for extra line to rails automatically go to index page of subject
    #render json: {status: 'SUCCESS', message: 'Loaded Subjects', data:@subjects},status: :ok
  end
################################################################
  def show
    #@subject = Subject.find(4) its not static so what 
    #if you see the link we are sending query string == On the internet, a query string is the part of a uniform resource locator (URL) which assigns values to specified parameters. The query string commonly includes fields added to a base URL by a Web browser or other client application, for example as part of an HTML form.
    #like http://localhost:3000/subjects/1
    #we are catching id throug params[:id] this sending by index template
    @subject = Subject.find(params[:id]) #that make us to available to our template show 
  end
################################################################
  def new
    @subject = Subject.new({:name => 'Default'}) #notic VISIBLE already have a false value because we gave it in database 
    @subject_count = Subject.count + 1 
    #because we are adding a new one in this 
    #and not to forget to add in create else part because there we also render new that will not have this list and give you an error
  end
################################################################
  def create
    #steps
    #instantite a new object using form 
    #save object
    #if save succeed, redirects to the index action
    #if fails redisplay the form so user can fix the problems 

    #@subject = Subject.new(params[:subject]) #problem of mass assignment FORBIDEN ATTRIBUTES ERROR
    @subject = Subject.new(subject_params)

    if @subject.save
      flash[:notice] = "Subject created Successfully."
      redirect_to(subjects_path) #return us to the index page which show all the subjects
    else
      @subject_count = Subject.count + 1
      render('new') #render just form template having already @subject and populate with old values which have validation error
      #user don't have to enter all that valus again 
    end
  end
################################################################
  def edit
    @subject = Subject.find(params[:id])
    @subject_count = Subject.count
  end
################################################################
  def update
    #steps
    #find object using form parameters
    #update the object
    #if save succeed, redirects to the show action
    #if fails redisplay the form so user can fix the problems 

    #
    @subject = Subject.find(params[:id])

    if @subject.update_attributes(subject_params)
      flash[:notice] = "Subject updated Successfully."
      redirect_to(subject_path(@subject)) # return to detail view of that subject mean show   
    else
      @subject_count = Subject.count 
      render('edit') #render just form template having already @subject and populate with old values which have validation error
      #user don't have to enter all that valus again 
    end
  end
################################################################
  def delete
     @subject = Subject.find(params[:id])
  end
################################################################
  def destroy
    @subject = Subject.find(params[:id])
    @subject.destroy #how ever we destroy this subject it is still available in frozen ruby object
    flash[:notice] = "Subject #{@subject.name} destroyed Successfully." 
    redirect_to(subjects_path)
  end
################################################################
  private
################################################################
  def subject_params
    params.require(:subject).permit(:name, :position, :visible)
  end
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/delete.html.erb
<%= link_to("<< Back to List", subjects_path, :class => 'back-link') %>

<div class="subjects delete">
  <h2>Delete Subject</h2>
  
  <%= form_for(@subject, :url => subject_path(@subject), :method => 'delete') do |f| %> 
<%# you can ommit the url part but not :method => delete you have to specify this  %>
    <p>Are you sure you want to permanently delete this subject?</p>

    <p class="reference-name"><%= f.object.name %></p>
    <%# notice f.object.name however sebject.name is totally workout for us fine %>

    <div class="form-buttons">
      <%= f.submit("Delete Subject") %>
    </div>

  <% end %>
</div>

app/views/subjects/edit.html.erb
<%= link_to("<< Back to List", subjects_path, :class => 'back-link') %>

<div class="subjects edit">
  <h2>Update Subject</h2>

  <%= form_for(@subject, :url => subject_path, :method => 'patch') do |f| %>
  <%# form_for(@subject) do |f| %>    
  <!-- #we dont have to specify them becuase you are post something and see rails route -->
    <%= error_messages_for(f.object) %>
    <%# this function is in our helper don't need to write it over and over for others page and sections%>
    <table summary="Subject form fields">
      <tr>
        <th>Name</th>
        <td><%= f.text_field(:name) %></td>
      </tr>
      <tr>
        <th>Position</th>
        <td><%= f.select(:position, 1..@subject_count) %></td>
      </tr>
      <tr>
        <th>Visible</th>
        <td><%= f.check_box(:visible) %></td>
      </tr>
    </table>

    <div class="form-buttons">
      <%= f.submit("Update Subject") %>
    </div>

  <% end %>
</div>

app/views/subjects/index.html.erb
<%
=begin%>
 <% if !flash[:notice].blank?  # its check for the nil but also for the empty strings %>
  <div class= "notice">
    <%= flash[:notice] %>
  </div>
<% end %>     FOR SHOWING ERRORS IF HAVE ANY 
<%            MOVE THIS BLOCK OF CODE FROM EVERY PAGE AND PASTE IT INTO OUR MASTER LAYOUT FOR NOT REPEATING OURSELVES
=end%>

<% @page_title = "All Subjects" %>

<%= link_to("<< Back to Menu", admin_path, :class => 'back-link') %>


<div class="subjects index">
  <h2>Subjects</h2>
  <%= image_tag("plus_sign.png", :size => '11x11', :alt => '+') %>
  <%# link_to("Add New Subject", 'subjects/new', :class => 'action new') %>
  <%= link_to("Add New Subject", new_subject_path , :class => 'action new') %>

  <table class="listing" summary="Subject list">
    <tr class="header">
      <th>Position</th>
      <th>Subject</th>
      <th>Visible</th>
      <th>Pages</th>
      <th>Actions</th>
    </tr>
    <% @subjects.each do |subject| %>
    <tr>
      <td><%= subject.position %></td>
      <td><%= subject.name %></td>
      <td class="center"><%= subject.visible ? 'Yes' : 'No' %></td>
      <td class="center"><%= subject.pages.size %></td>
      <td class="actions">
        <%# link_to("Show", 'subjects#{subject.id}', :class => 'action show') %>
        <%# link_to("Show", {:controller => 'subjects' , :action => 'show', :id => subject.id }, :class => 'action show') %>
        <%= link_to("View Pages", pages_path(:subject_id => subject.id), :class => 'action show') %>
        <%= link_to("Show", subject_path(subject), :class => 'action show') %>
        <%= link_to("Edit", edit_subject_path(subject), :class => 'action edit') %>
        <%= link_to("Delete", delete_subject_path(subject), :class => 'action delete') %>
      </td>
    </tr>
    <% end %>
  </table>
</div>

app/views/subjects/new.html.erb
<%= link_to("<< Back to List", subjects_path, :class => 'back-link') %>

<div class="subjects new">
  <h2>Create Subject</h2>

  <%= form_for(@subject, :url => subjects_path, :method => 'post') do |f| %>
  <%# form_for(@subject) do |f|     we dont have to specify them becuase you are post something and see rails route %> 
    <%= error_messages_for(f.object) %>
    <%# this function is in our helper don't need to write it over and over for others page and sections%>
    <table summary="Subject form fields">
      <tr>
        <th>Name</th>
        <td><%= f.text_field(:name) %></td>
      </tr>
      <tr>
        <th>Position</th>
        <td><%= f.select(:position, 1..@subject_count) %></td>
        <!-- using select :subject is optional here -->
      </tr>
      <tr>
        <th>Visible</th>
        <td><%= f.check_box(:visible) %></td>
        <%# check box is a special beahviour in html if you not check it it doesn't include in form submission but in rails it put a hidden field for checkbox with the value of 0 and 1 NEAT TRICK  %>
      </tr>
    </table>

    <div class="form-buttons">
      <%= f.submit("Create Subject") %>
    </div>

  <% end %>
</div>

<%# 
form_for(@subject, :html => {:multipart => true}) do |f| 
  
  f.label(:name)
  f.text_field(:name, :size => 40, :maxlength => 40)
  f.password_field(:password, :size => 40)
  f.hidden_field (:token, 'af343krkerj34')

  f.text_area(:description, :size => "40x5") # :col and :rows

  f.radio_button(:content_type, "Text")
  f.radio_button(:content_type, "HTML")

  f.check_box(:visible)
    # check box is a special beahviour in html if you not check it it doesn't include in form submission but in rails it put a hidden field for checkbox with the value of 0 and 1 NEAT TRICK  
  f.file_field(:logo) # requires :multipart => true 

end
%>

app/views/subjects/show.html.erb
<%= link_to("<< Back to List", subjects_path, :class => 'back-link') %>

<div class="subjects">
  <h2>Show Subject</h2>

  <table summary="Subject detail view">
    <tr>
      <th>Name</th>
      <td><%= @subject.name %></td>
    </tr>
    <tr>
      <th>Position</th>
      <td><%= @subject.position %></td>
    </tr>
    <tr>
      <th>Visible</th>
      <td><%= @subject.visible ? 'true' : 'false' %></td>
    </tr>
    <tr>
      <th>Created</th>
      <td><%= @subject.created_at.strftime("%d/%m/%Y at %I:%M%p") %></td>
    </tr>
    <tr>
      <th>Updated</th>
      <td><%= @subject.updated_at.strftime("%d/%m/%Y at %I:%M%p") %></td>
    </tr>
  </table>

</div>